spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opr_mgmt
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect 
    show-sql: true    
  application:
    name: team-data-management
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: SOPRA
    enabled: true
    
    
server:
  port: 9000
  
