spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opr_mgmt
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect     
    show-sql: true
  application:
    name: delivery-portfolio
  liquibase:
    enabled: false
server:
  port: 8090
 