spring:
  application:
    name: gateway-server
     
zuul:
  prefix: /oprmgmt
  retryable: true
  routes:
    tdm:
      path: /tdm/**
      service-id: team-data-management
    delivery-portfolio:
      path: /dpo/**
      service-id: delivery-portfolio

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true
    
server:
  port: 8765 