spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mock-opm-database?useSSL=false
    username: root
    password: root
  #  driver-class-name: org.postgresql.Driver
  application:
    name: team-data-management
  
  jpa:
    #properties:
    # hibernate:
     #   jdbc:
      #    lob:
       #     non_contextual_creation : true  
   hibernate:
      ddl-auto: create-drop
      
  # database-platform: org.hibernate.dialect.PostgreSQL9Dialect 
   show-sql: true  
   
    
    
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.224.24.218:8761/eureka/
      #  defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  
